const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('app', {
  scanProfiles: () => ipcRenderer.invoke('scan-profiles'),
  saveProfileConfig: (dir, data) => ipcRenderer.invoke('save-profile-config', dir, data),
  checkDuplicateName: (dir, name) => ipcRenderer.invoke('check-duplicate-name', dir, name),
  deleteProfile: (profilePath, dir, name) => ipcRenderer.invoke('delete-chrome-profile', profilePath, dir, name),
  createShortcut: (dir, name) => ipcRenderer.invoke('create-shortcut', dir, name),
  deleteShortcut: (name) => ipcRenderer.invoke('delete-shortcut', name),
  openProfile: (dir) => ipcRenderer.invoke('open-profile', dir),
  openProfileUrl: (dir, url) => ipcRenderer.invoke('open-profile-url', dir, url),
  openProfilesBatch: (dirs) => ipcRenderer.invoke('open-profiles-batch', dirs),
  killAllChrome: () => ipcRenderer.invoke('kill-all-chrome'),
  checkShortcutExists: (name) => ipcRenderer.invoke('check-shortcut-exists', name),
  pickUserDataFolder: () => ipcRenderer.invoke('pick-user-data-folder'),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  getGroups: () => ipcRenderer.invoke('get-groups'),
  saveGroups: (groups) => ipcRenderer.invoke('save-groups', groups),
  getGroupSubs: () => ipcRenderer.invoke('get-group-subs'),
  saveGroupSubs: (subs) => ipcRenderer.invoke('save-group-subs', subs),
  createChromeProfile: (name, groups, subGroups, notes) => ipcRenderer.invoke('create-chrome-profile', name, groups, subGroups, notes),
  getAvatarDataUrl: (p) => ipcRenderer.invoke('get-avatar-data-url', p),
  getCacheSize: (profilePath) => ipcRenderer.invoke('get-cache-size', profilePath),
  getAllCacheSizes: () => ipcRenderer.invoke('get-all-cache-sizes'),
  clearCache: (profilePath) => ipcRenderer.invoke('clear-cache', profilePath),
  clearAllCache: () => ipcRenderer.invoke('clear-all-cache'),
  removeBadExtensions: () => ipcRenderer.invoke('remove-bad-extensions'),
  getProfileHistory: (profilePath) => ipcRenderer.invoke('get-profile-history', profilePath),
  getGoogleAccounts: (profilePath) => ipcRenderer.invoke('get-google-accounts', profilePath),
  getSocialStatus: (profilePath, sites) => ipcRenderer.invoke('get-social-status', profilePath, sites),
  getSocialStatusBatch: (profilePaths, sites) => ipcRenderer.invoke('get-social-status-batch', profilePaths, sites),
  getSocialSites: () => ipcRenderer.invoke('get-social-sites'),
  saveSocialSites: (sites) => ipcRenderer.invoke('save-social-sites', sites),
  renameGroupInProfiles: (oldName, newName) => ipcRenderer.invoke('rename-group-in-profiles', oldName, newName),
});
